// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTGbcPgrNO_W2Y9ptggDFBKz78dSviXA',
    appId: '1:442697352180:web:d289bfd8c8467872006fa1',
    messagingSenderId: '442697352180',
    projectId: 'shoppinglist-ad6fd',
    authDomain: 'shoppinglist-ad6fd.firebaseapp.com',
    storageBucket: 'shoppinglist-ad6fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsTHZ5f6agIs3kYUCpWmMBEgNH74aTM60',
    appId: '1:442697352180:android:a87d94ddce354a51006fa1',
    messagingSenderId: '442697352180',
    projectId: 'shoppinglist-ad6fd',
    storageBucket: 'shoppinglist-ad6fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRygQb6brYS2qRYkRYxvLPj-q0U-V61PI',
    appId: '1:442697352180:ios:2da487a49c6fb3d5006fa1',
    messagingSenderId: '442697352180',
    projectId: 'shoppinglist-ad6fd',
    storageBucket: 'shoppinglist-ad6fd.appspot.com',
    iosClientId: '442697352180-rhsod3mu42llp51hoi3m2neeiak99oq3.apps.googleusercontent.com',
    iosBundleId: 'com.herveguigoz.dashlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRygQb6brYS2qRYkRYxvLPj-q0U-V61PI',
    appId: '1:442697352180:ios:2da487a49c6fb3d5006fa1',
    messagingSenderId: '442697352180',
    projectId: 'shoppinglist-ad6fd',
    storageBucket: 'shoppinglist-ad6fd.appspot.com',
    iosClientId: '442697352180-rhsod3mu42llp51hoi3m2neeiak99oq3.apps.googleusercontent.com',
    iosBundleId: 'com.herveguigoz.dashlist',
  );
}